// apps/web/src/components/ledger/rotating-word.tsx
"use client";

import { useEffect, useState } from "react";

const REST_MS = 3200;
const ERASE_MS = 60;
const KEY_MS = 110;

type Phase = "rest" | "erase" | "type";

/** A headline word that is erased and retyped, letter by letter, inside a fixed-width slot. */
export function RotatingWord({
  words,
  paused = false,
}: {
  words: string[];
  paused?: boolean;
}) {
  const reduced = useReducedMotion();
  const active = !paused && !reduced;
  const [index, setIndex] = useState(0);
  const [phase, setPhase] = useState<Phase>("rest");
  const [text, setText] = useState(words[0] ?? "");
  const target = words[index] ?? "";
  const slot = Math.max(...words.map((w) => w.length));

  useEffect(() => {
    if (reduced) {
      setText(target);
      return;
    }
    if (phase === "rest") {
      if (!active) return;
      const id = setTimeout(() => {
        setIndex((i) => (i + 1) % words.length);
        setPhase("erase");
      }, REST_MS);
      return () => clearTimeout(id);
    }
    if (phase === "erase") {
      if (text.length === 0) {
        setPhase("type");
        return;
      }
      const id = setTimeout(() => setText(text.slice(0, -1)), ERASE_MS);
      return () => clearTimeout(id);
    }
    if (phase === "type") {
      if (text.length >= target.length) {
        setPhase("rest");
        return;
      }
      const id = setTimeout(
        () => setText(target.slice(0, text.length + 1)),
        KEY_MS + Math.random() * 60,
      );
      return () => clearTimeout(id);
    }
  }, [phase, text, target, reduced, active, words.length]);

  return (
    <span
      className="inline-block whitespace-nowrap text-left align-baseline font-medium font-mono"
      style={{ width: `${slot}ch` }}
    >
      <span className="inline-block rounded-[0.08em] bg-line px-[0.12em]">
        {text}
      </span>
    </span>
  );
}

function useReducedMotion() {
  const [reduced, setReduced] = useState(false);
  useEffect(() => {
    const mq = window.matchMedia("(prefers-reduced-motion: reduce)");
    const sync = () => setReduced(mq.matches);
    sync();
    mq.addEventListener("change", sync);
    return () => mq.removeEventListener("change", sync);
  }, []);
  return reduced;
}

// apps/slides/components/RotatingWord.vue
<script setup lang="ts">
import { onBeforeUnmount, onMounted, ref } from "vue";

const REST_MS = 3200;
const ERASE_MS = 60;
const KEY_MS = 110;

const props = defineProps<{ words: string[] }>();

const text = ref(props.words[0] ?? "");
const slot = Math.max(...props.words.map((w) => w.length));
let timer: ReturnType<typeof setTimeout> | undefined;
let index = 0;

onMounted(() => {
  if (matchMedia("(prefers-reduced-motion: reduce)").matches) return;
  const at = (ms: number, next: () => void) => {
    timer = setTimeout(next, ms);
  };
  const rest = () =>
    at(REST_MS, () => {
      index = (index + 1) % props.words.length;
      erase();
    });
  const erase = () =>
    at(ERASE_MS, () => {
      if (text.value.length === 0) return type();
      text.value = text.value.slice(0, -1);
      erase();
    });
  const type = () =>
    at(KEY_MS + Math.random() * 60, () => {
      const target = props.words[index] ?? "";
      if (text.value.length >= target.length) return rest();
      text.value = target.slice(0, text.value.length + 1);
      type();
    });
  rest();
});

onBeforeUnmount(() => clearTimeout(timer));
</script>

<template>
  <span
    class="inline-block whitespace-nowrap text-left align-baseline font-mono font-medium"
    :style="{ width: `${slot}ch` }"
  >
    <span class="inline-block rounded-[0.08em] bg-line px-[0.12em]">{{
      text
    }}</span>
  </span>
</template>
